### ISSUE TITLE
Window dimensions aren't saved

### ISSUE THREAD

**Issue by NicolasConstant** [NicolasConstant/sengi-electron#14]
https://github.com/NicolasConstant/sengi/issues/502

**Comment by anantshri** [comment]
duplicate of #3

**Comment by anantshri** [comment]
Just checking, Is this moved into release already. coz the latest release version(1.8.0) still doesnt remember the dimension and always start in one column mode.

**Comment by NicolasConstant** [comment]
No it's not, but since this issue is a duplicate (indeed), I just closed it.
