### ISSUE TITLE
Repeated TypeError from 'reblogs'

### ISSUE THREAD

**Issue by HG-Dev** [NicolasConstant/sengi-electron#17]
`ERROR TypeError: Cannot read properties of null (reading 'reblog')`

Affects both in-browser and desktop versions (1.5.0).

The above error is occurring frequently with two of my more active accounts' notifications columns, such that toots are not displayed in the column, and columns created to its right are not updated.

Might this have something to do with optional data being used to render quote boosts...?
I'd like to delve further into the matter, but I'm not a web programmer; the minified JavaScript is inpenetrable to me.

<img width="450" alt="image" src="https://github.com/NicolasConstant/sengi-electron/assets/29112495/d4f440c2-9b11-4484-ab5c-bf5911dc1351">

**Comment by NicolasConstant** [comment]
since it's a webapp issue, closing this one here.

**Comment by HG-Dev** [comment]
Ah, I see, this was the wrong repository. Sorry!

**Comment by NicolasConstant** [comment]
no problem, I understand the two repo can be misleading. 😉
