### ISSUE TITLE
Not applying filters (Mastodon/glitch-soc)

### ISSUE THREAD

**Issue by Jenetrix** [NicolasConstant/sengi-electron#22]
Sengi is not applying filters created server-side in default mastodon & glitch-soc.
This is happening even after clearing cache, logging out/back in.
(Sengi 1.8.0 Windows)

**Comment by NicolasConstant** [comment]
duplicate of https://github.com/NicolasConstant/sengi/issues/414

(the app code is hosted in `NicolasConstant/sengi`, some info [here](https://github.com/NicolasConstant/sengi/wiki/Why-installed-version-is-different-of-the-app-version%3F))
